### ISSUE TITLE
Cross-checking solutions

### ISSUE THREAD

**Issue by markalexander** [Pythonese/gsa-ultra-2018#1]
Hey :)

I got 12 out of 13 correct with this submission:

https://github.com/markalexander/gsa-ultra-2018

If you're curious, I cross-checked our answers and it seems like 9d and 11d are the ones that don't match.

The difference between our 11d answers is that I treated e.g 100 as almost square since removing '1' gives '00' which I cast to 0.  To be honest, I actually didn't think about this at the time, but I got lucky and my method matches the problem description.  From what I can see, your method will end up with e.g. 100, 101, 104 as being not almost-square.

So it seems that your 11d is the one that's wrong, and my 9d is wrong.

Out of curiosity by the way, when did you end up submitting?  I have no idea how close I might have come (assuming I had correct answers, at least).  I submitted around an hour or two before the deadline, but I suspect lots of people did before then.

**Comment by AlexMorson** [comment]
Hi!

Thank you for going through my answers, I was very curious as to what I got wrong!

Ah, yes, that makes sense. And rereading the problem statement I see this: "Observe that 20 and 200 are almost-square integers as well, as removing 2 from them gives 0" which should have made it clear to me.

With regards to your 9d, it seems like you may not have realised that there could be multiple of each colour of key in the maze. I noticed this because your `get_waypoints` function returns the `dict` of the results, which means only the positions of one of each key is considered.

I submitted my answers a day and a half before the deadline. Maybe I should have spent some more time reading through the problem descriptions before submitting!

**Comment by markalexander** [comment]
Ah, that's true; a silly oversight on my part.  Thanks!

So close, yet so far.  I won't be eligible to compete next year, but good luck if you're going to try it again.

**Comment by AlexMorson** [comment]
Thank you!
